language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp travis_settings.xml $HOME/.m2/settings.xml

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  provider: bintray
  file: bintray.json
  skip_cleanup: true
  user: vaughnvernon
  on:
    branch: master
  passphrase:
    secure: DWcRNjvNOjEB3iTIEmCIipVSPX12SXUiUgHzF4CtH7ZxyQzzsJzUsVweycrPcOe65SLZXZT4pkCMZiqd7joad3sG/J3s8SK8RAnuqqcPCn0or3yQrXqWJI6ux8QRV6vVb9DsRJNWQfu+PbsFCoQ1FqEaa60psjBwMeC2lbWU5ZwLxyuumuCDGlTrCJQHPZ6kVSevf/lCU2MO2KHSS76zTSKgPrE9p93Wfq4UswZWy+WRzBqYKosiu9pM0N1YExQxkLPZm128X8a+2C/nhCXSkEN9c2IOHim7w73eihAiQC63B4xKFpsyoZaPURdeEArDS0n5FvFOAlOF1wvIujqwBwsD+3AOMTNhM19iuSZ8S91LVewXEfbCj1VCXknnq3kYSm7w6IUdEfjDX4wYBwaIlyIv8tBHU9qD04u4aUFqA+BpykhfYXXtLW+scWedjbA4ALbK79sz1BIG/pBFP6Vch6dMAA2MF2z2Qtyq/hEZhItuDi+rl9iiwvUfbDRHnBvbPr7+qygNvaGIl/hflaQLejckdJ7nw8TJf5IXmJpZMsjtKYW29t66W2Bipbllc0HqzMwfG1+WAkIItNJKRSHkbbL7ggkgED9py8sLKs+ITFMUKBghfeOEv420v31r5x7MjN3hK+mokxz0IDmWseXKeZ+6EYEDefmia17hEkCJiiM=
  key:
    secure: X+mTh3k44uSkbUAxjOoy6F6m5iti395m1q6TzsEQ+MIiyrvr+dcH1PnJs0i1fLuU6OANbUqkSNSuROaKFQ9nS5puuqiM8bJj0htIpsD92js2tXuVubqXEvx0UyjZ8ZUwoWnQJxDyiL6XWkQmDR208YTAQBg/WBWyrIwhWZc1QrtgJsFWE5fkExhoh6LDhfyWoEB33U8p1lNcIXQrdnwCYycmDOuT9X4aAsSBw/qucnR34yZ0eA8RqBGRg5GDDrk0AqzLnpuexyW+B3SmnPn0GK6wmxscSpgrb+XB+uD71GZHMw5scj6Z2bRbjRwcWDFUWPwOYcbxXOd0w7koZ+ZHTUAWE7MIA85s9Bi30HJTWaIbU/lV61DDvNmoPcXE2HI1gxm5OrFxJRd0q4/HWFYV6hxO9rYhbm6EDorkIh5XGP56wzT8/qjRW8ZNSmiEQuzh7CxFPsqYggfmH8Vq7alpxKc+dfDMj/02/xWqFjprG9KTI5WAWc6UL4HqLmMS2G7OoMnyF6F4NsYnGMQ+vducv+MKbFHD4KYsvQG7KFoItVjy+LrszZfINMLdqCzJ+iyDIHJmHhdxLdUvtrIZGiU//fEz3Pd53FxxjXM2vwY7mvMglTg33haH/7cE+TD6I+xDA02CjN9TcTsoMYEI578wJPqAHv4Q+/E/vKI6FziayIk=
notifications:
  slack:
    secure: iyrSGRv5vxzl8Frf3MiYPt7k85WYhGWv4GWAtHGHJ4DbCB5hrCTdFQjotFLQPhL5VYaZrDQuJKCcmrPcIJa782Zet3pkM1ho+G9o6kR64enKM86XGLLSSmyLx7F4VpG/ftHoXjgH3gd53OFTNpF+kd8XaqiPOax7+Bq6xshLcnR+m4cFNkkmn+EjkCQsNRqLVKghRtKMPjUm5NmGjJtiljUfZgMRJiQGSD3LYfXGzFg05YMTYXpn+WJZJ3f4u7d//KLZN1LgDrDXZwjz8j9d1bJA9TaDum5zU+/ptF5Et+xqq05/h2J2vJmeeO6ogFmn3H9wiiWNSn4LGnJni7AjzyLIc+WIxr8EQDQBzIYnapuVhSiD0Vq+TprXvegOFfQypnm8zxQ7UUzEeoMgqdQjkbUtP26s/HqU+D7zE/KldkBwLucT8DPdNL2WRT6NjjrlN01B/TaVca21dslae4CjGbgPnHBe+3Xa9VYSREy+25YvXp++Oa9xI4HOhpG7QXfWTrkXtdD0uhXBL/cJe4jIzjgEsvJPUs+hB8tpRX588VHmbgdJxM4O8V/uYbDMbUg9suczxd2dC8GxbNRjY8JYW/L2mb9t5+bo3qmE4HGwF9vNZR2s5MLHiwyqyR4cjRZThN2tQrLvX8otpxdC7mZoTOS1A6Bqvkqwrewu+nwYJaQ=
