language: java
dist: trusty

before_install:
  - rm -rf $HOME/.m2/repository/io/vlingo
  - cp .travis/settings.xml $HOME/.m2/settings.xml

script:
  - mvn install

before_cache:
  - rm -rf $HOME/.m2/repository/io/vlingo
cache:
  directories:
    - $HOME/.m2/repository

deploy:
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: "mvn deploy -DskipTests"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    secure: iyrSGRv5vxzl8Frf3MiYPt7k85WYhGWv4GWAtHGHJ4DbCB5hrCTdFQjotFLQPhL5VYaZrDQuJKCcmrPcIJa782Zet3pkM1ho+G9o6kR64enKM86XGLLSSmyLx7F4VpG/ftHoXjgH3gd53OFTNpF+kd8XaqiPOax7+Bq6xshLcnR+m4cFNkkmn+EjkCQsNRqLVKghRtKMPjUm5NmGjJtiljUfZgMRJiQGSD3LYfXGzFg05YMTYXpn+WJZJ3f4u7d//KLZN1LgDrDXZwjz8j9d1bJA9TaDum5zU+/ptF5Et+xqq05/h2J2vJmeeO6ogFmn3H9wiiWNSn4LGnJni7AjzyLIc+WIxr8EQDQBzIYnapuVhSiD0Vq+TprXvegOFfQypnm8zxQ7UUzEeoMgqdQjkbUtP26s/HqU+D7zE/KldkBwLucT8DPdNL2WRT6NjjrlN01B/TaVca21dslae4CjGbgPnHBe+3Xa9VYSREy+25YvXp++Oa9xI4HOhpG7QXfWTrkXtdD0uhXBL/cJe4jIzjgEsvJPUs+hB8tpRX588VHmbgdJxM4O8V/uYbDMbUg9suczxd2dC8GxbNRjY8JYW/L2mb9t5+bo3qmE4HGwF9vNZR2s5MLHiwyqyR4cjRZThN2tQrLvX8otpxdC7mZoTOS1A6Bqvkqwrewu+nwYJaQ=
